fix(docker interval) : augmente l'intervalle de temps avant le premier health check + ajoute des logs en cas d'erreur

diff --git a/.github/workflows/docker-dev-test.yaml b/.github/workflows/docker-dev-test.yaml
--- a/.github/workflows/docker-dev-test.yaml
+++ b/.github/workflows/docker-dev-test.yaml
@@ -77,14 +77,27 @@ jobs:
         JWT_SECRET: ${{ secrets.DOCKERHUB_TEST_JWT_SECRET }}
       timeout-minutes: 10
 
-    #8. Login to DockerHub
+    #9. Print logs for all containers on failure
+    - name: Print database logs on failure
+      if: failure()
+      run: docker logs database || true
+
+    - name: Print backend logs on failure
+      if: failure()
+      run: docker logs backend-dev || true
+
+    - name: Print frontend logs on failure
+      if: failure()
+      run: docker logs frontend-dev || true
+
+    #10. Login to DockerHub
     - name: Login to DockerHub
       uses: docker/login-action@v3
       with: 
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-    #9. Build and push dev image 
+    #11. Build and push dev image 
     - name: Build and push docker dev image
       uses: docker/build-push-action@v6 
       with: 
